.github/workflows/python-package.yml
README.md
requirements.txt
tests/test_catalog.py

Adds test which walks the entire catalog (max depth 10) and ensures the
data can be accessed and loaded from each data-source.

Add test to validate entire catalog

---

.github/workflows/python-package.yml
README.md
catalog.yml
p3/axbts.yaml
p3/flight-level.yaml
p3/isotope-analyzer.yaml
p3/main.yaml
p3/remote-sensing.yaml
p3/w-band-radar.yaml
p3/wsra.yaml
requirements.txt
tests/test_catalog.py

I should have started with a branch instead of committing to master directly, my apologies. 
The CI tests appear to be failing during item.discover(). This works on my local installation but the CI is complaining about a missing module "aiohttp". I may try to add this next.

Tests for netcdf plugins

---

barbados/bco.yaml
barbados/main.yaml
catalog.yml

Adds CORAL LIDAR (BCO) to catalog fetching data from AERIS

Add entry for CORAL LIDAR at BCO

---

HALO/BAHAMAS_QL.yaml

The source path on Aeris has been changed.

BAHAMAS: 2020 has been removed from source path

---

HALO/bacardi.yaml
HALO/bacardi_irradiances.yaml
HALO/main.yaml

new cataloque entry for BACARDI dataset

add entry for BACARDI

---

HALO/smart_irradiances.yaml

new files with corrected time shift have been uploaded on Aeris

update SMART urls to latest version of files

---

HALO/wales/wales_cloudtop.yaml

Martin Wirth put an updated version V1.1 on AERIS that is CF conform and includes slight improvements in the variables and attributes.

update WALES cloud parameter file to V1.1

---

HALO/bahamas_unified.yaml
HALO/dropsondes_unified.yaml
HALO/radar_unified.yaml
HALO/radiometer_unified.yaml

The HALO unified dataset got a new version.

update HALO unified v0.7 -> v0.9

---

MS-Merian/FMCW94_RPG.yaml
MS-Merian/main.yaml

I prepared the main.yaml and Wband.yaml files to be included for having also Wband radar data from merian on the eurec4a intake. Please check if it works/has problems :)

merian Wband yaml files to check

---

HALO/unified/MWR_cloud_mask_unified.yaml
HALO/unified/MWR_retrievals_unified.yaml

After discussing with Geet, Andreas and I applied the 1.06 moisture correction for the dropsondes. This impacts the MWR BT offset correction and thus the retrieval and MWR cloud mask.

Update MWR retrieval due to recalibration

---

barbados/bco.yaml

This PR adds the Ka-Band radar dataset from the EUREC4A time period 😄

+ BCO radar dataset

---

P3/isotope-analyzer-water-vapor-Isotope-Ratios-1hz.yaml
P3/isotope-analyzer-water-vapor-Isotope-Ratios-5hz.yaml
P3/isotope-analyzer.yaml
WG/WG245.yaml
WG/WG247.yaml

Update wave gliders data version. Also add P3 isotope-analzer water vapor isotope ratios

wave glider and P3 isotope ratio update

---

barbados/bco.yaml

Add BCO weather sensor data

---

Simulations/ICON/LES_CampaignDomain_highCCN.yaml

Add synthetic radar output of ICON LES simulation output
- output of high CCN experiment

Add synthetic radar at BCO (ICON LES exp1)

---

Simulations/ICON/LES_CampaignDomain_control.yaml

Adds pressure level output of control experiment.

Add ICON LES output on selected pressure levels

---

.github/workflows/python-package.yml

CI: run ipfs local node

---

Simulations/ICON/SRM.yaml
Simulations/ICON/main.yaml

- this will be the start of adding some ICON-SRM output to the catalog

add meteograms of ICON-SRM

---

SWIFT/SWIFT16.yaml
SWIFT/SWIFT17.yaml
SWIFT/SWIFT22.yaml
SWIFT/SWIFT23.yaml
SWIFT/SWIFT24.yaml
SWIFT/SWIFT25.yaml

Files at version 2.3 disappeared from THREDDS.

update SWIFT v2.3 -> v2.4

---

Simulations/DALES/botany.yaml
Simulations/DALES/botany_dx100m.yaml
Simulations/DALES/botany_dx100m_nx1536.yaml
Simulations/DALES/botany_dx100m_nx768.yaml
Simulations/DALES/main.yaml
Simulations/main.yaml

Add catalog entry for botany simulations.

initial botany commit

---

requirements.txt

This should be a hotfix for #121. Hopefully newer releases of netCDF won't have this bug 😬.

restrict netCDF4 even more

---

P3/isotope-analyzer-water-vapor-Isotope-Ratios-1hz.yaml
P3/isotope-analyzer-water-vapor-Isotope-Ratios-5hz.yaml

Update version of P3 isotope analyser water-vapour-isotope ratios v1.0 -> v1.1

---

requirements.txt

Exclude netCDF4 version 1.6.2

---

.github/workflows/python-package.yml
.github/workflows/weekly_tests.yml

Deprecation warnings are raised within the GitHub action. This PR updates the actions to their current version.

update GitHub actions

---

requirements.txt

Exclude netcdf version 1.6.4 and 1.6.5

---

CONTRIBUTING.md

This PR adds our agreement in #144 to the `CONTRIBUTION.md`

Add catalog entry guidelines

---

.github/workflows/python-package.yml
.github/workflows/weekly_tests.yml
CHANGELOG.md

Bumping IPFS version to add support for IPNI lookups and other enhancements that speed up file lookup and retrieval

Update IPFS version

---

CHANGELOG.md
Meteor/LIMRAD94.yaml

Update default version of RV-Meteor LIMRAD94 radar data

---

CHANGELOG.md
P3/w-band-radar.yaml

change v1.0 to v2.0
fixes #166

update p3 w-band radar version
