eurec4a/eurec4a-intake

- HALO/BAHAMAS.yaml
- HALO/main.yaml
- HALO/specmacs/experimental.yaml
- HALO/specmacs/main.yaml
- HALO/unified.yaml
- P3/isotope-analyzer.yaml
- P3/main.yaml
- barbados/main.yaml
- catalog.yml
- dropsondes.yaml
This is the official name from the [intake plugin directory](https://intake.readthedocs.io/en/latest/plugin-directory.html?highlight=yaml_file_cat#plugin-directory).
While it is also possible to directly specify python classes, this seems
to be odd for a general catalog. In particular, I could imagine that we
want to read intake catalogs from different programming languages at
some point in time and then hard coded python module names will not be
beneficial.
> use yaml_file_cat as driver for nested catalogs

- swifts.yml
The swift files noted in the catalog are gone. Instead, there seem to be new files `v2.1` available on the [NOAA server](https://psl.noaa.gov/thredds/catalog/Datasets/ATOMIC/data/swift_drifters/catalog.html). I updated the intake catalog entry accordingly and hope that the tests run through again.
> update swift entry to new file version `v2.1`

- HALO/main.yaml
- HALO/velox.yaml
- HALO/velox_cloudmask.yaml
I would like to add the cloud mask product from HALO's IR imager VELOX. Unfortunately AERIS is unavailable at the moment. I will renew this pull request as soon as AERIS is up again and I tested the file entries.
> add cloudmasks from HALO's IR imager VELOX

- requirements.txt
Since the newly released version of intake 0.6.1, `to_dask()` doesn't
work anymore without this install secion. This is most likely the
current primary reason for #45 to fail.
> changed intake requirement to intake[dataframe]

- HALO/specmacs/cloudmaskSWIR.yaml
This PR updates the specMACS cloudmaskSWIR to version 2. Currently there's only one file (for flight `HALO-0202`) available, thus the PR is started as a draft and will be updated as new files become available.
> specMACS cloudmaskSWIR v2

- radiosondes.yml
This includes a change from denby.io to Aeris.
see #26 for some discussion about this
> updated radiosondes to v3

- P3/WSRA.yaml
- P3/axbts.yaml
- P3/flight-level.yaml
- P3/isotope-analyzer-water-vapor-1hz.yaml
- P3/isotope-analyzer-water-vapor-5hz.yaml
- P3/remote-sensing.yaml
- P3/w-band-radar.yaml
Updated all the NCEI data URLs in the P3 folder.
> Update ATOMIC URLs

- JOANNE/main.yaml
- tests/test_catalog.py
The datasets don't work nicely over OPeNDAP and accessing them directly
via netCDF seems to be the most pragmatic choice.
See also #78 and eurec4a/how_to_eurec4a#69.
> JOANNE: access netCDF files directly

- C3ONTEXT/C3ONTEXT.yaml
- catalog.yml
This pull requests adds the **C<sup>3</sup>ONTEXT** dataset described in [Schulz (2022)](https://doi.org/10.5194/essd-2021-427) to the this intake catalog.
This would bring us one step closer to quickly retrieve the observed meso-scale patterns of shallow convection in January-February 2020 for any requested position and time.
> + C3ONTEXT dataset

- Simulations/ICON/LES_CampaignDomain_control.yaml
This PR adds further output of the ICON LES simulations to the catalog
> ICON LES: add surface DOM02 output for controlRun

- barbados/bco.yaml
How about some MRR data from the BCO? I thought I chunk the data that is available [on AERIS](https://observations.ipsl.fr/aeris/eurec4a-data/BARBADOS/BCO/MRR/v1.0.0/), pack it into a neat zarr file and provide it via IPFS. Currently, it's only pinned locally but am happy to pin it elsewhere.
> Add BCO MRR data

- barbados/bco.yaml
- change BCO Ka-band radar data source from AERIS OpenDAP server to DKRZ SWIFT storage
- the OpenDAP protocol is not made for this relatively large dataset and causes problems when using it in daily research
> BCO Ka-band radar: change data location/protocol

- Simulations/ICON/LES_CampaignDomain_control.yaml
currently provided pressure level data is of little value
as its levels are in the upper troposphere and stratosphere
> ICON-LES control: remove pressure level data

- requirements.txt
This version seems to come with curl certificate issues.
This should fix #108, #109, #110 and #111.
> exclude netCDF-Python v1.6.0

- HALO/BAHAMAS_PositionAttitude.yaml
- HALO/BAHAMAS_QL.yaml
- HALO/bacardi_irradiances.yaml
- HALO/smart_irradiances.yaml
- HALO/specmacs/centroids.yaml
- HALO/specmacs/mesh.yaml
- HALO/specmacs/points.yaml
- HALO/unified/MWR_retrievals_unified.yaml
- HALO/unified/bahamas_unified.yaml
- HALO/unified/dropsondes_unified.yaml
- HALO/unified/radar_unified.yaml
- HALO/unified/radiometer_unified.yaml
- HALO/wales/wales_adepg.yaml
- HALO/wales/wales_bsrg.yaml
- HALO/wales/wales_bsri.yaml
- HALO/wales/wales_wv.yaml
- Meteor/LIMRAD94.yaml
- SD/SD-1026.yaml
- SD/SD-1060.yaml
- SD/SD-1061.yaml
- barbados/BCO/bco.yaml
- radiative_profiles.yml
- radiosondes.yml
- requirements.txt
- satellites/goes16.yaml
Pydap was causing troubles on an on and as we require netCDF anyways, we could also just use netCDF for accessing opendap resources. This PR sets all opendap resources to be accessed via netCDF.
During creation of this PR, another issue surfaced: some netCDF datasets are incompatible with the classic data model of netCDF (which is assumed to be the opendap data model by several clients). This PR changes access to the affected datasets to direct download of the original netCDF files (using `simplecache`) and opens those files as local netCDF files. I expect this to be a good trade-off, as the relevant netCDF files are rather small (several MB).
> Remove pydap dependency

- SVP/SVP-BSW-3101569.yaml
- SVP/SVP-BSW-3101570.yaml
- SVP/SVP-BSW-3101571.yaml
- SVP/SVP-BSW-3101572.yaml
- SVP/SVP-BSW-3101573.yaml
- SVP/SVP-BSW-3101574.yaml
- SVP/SVP-BSW-3101575.yaml
- SVP/SVP-BSW-3101576.yaml
- SVP/SVP-BSW-3101577.yaml
- SVP/SVP-BSW-3101578.yaml
- tests/test_yaml_files.py
The `TSWindPres` data from the `SVP`s was not availaible in the catalog due to incorrectly formatted yaml files.
This PR fixes this and updates `SVP-BSW-3101572` to version 2, because v1 disappeared on thredds.
In order to prevent futher errors of this kind, this PR also includes a new unit test which checks if unexpected keys are found in the yaml catalog files.
> fix missing TSWindPres of SVP

- WG/WG245.yaml
- WG/WG247.yaml
Data at version 2.3 disappeared from the THREDDS server.
> update waveglider v2.3 -> v2.4

- tests/test_catalog.py
discover is seemingly not implemented for all data sources, thus this
test can fail for the wrong reasons. Until discover is implemented for
all sources (if that happens at all) we'll have to specialize (meta-)
data loading in tests to each driver.
fixes #102
> remove item.discover() in tests

- .github/workflows/python-package.yml
- .github/workflows/weekly_tests.yml
The [current failure](https://github.com/eurec4a/eurec4a-intake/actions/runs/3167336245/jobs/5157754971#step:5:37792) of the weekly test made me think that it could be a good time to finally switch to python3.8 for the tests.
> change python version to 3.8

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- RELEASING.md
This PR contains a draft of several new files:
* `CONTRIBUTING.md`: (mostly for new contributors), how to add things
* `CHANGELOG.md`: a changelog, to help us with new version numbers
* `RELEASING.md`: (mostly for maintainers), how to make a new release
I consider this as an early stage draft towards solving #30. I didn't find enough time to polish this, but my plan would be, that these files should reflect the outcome of what we discuss in #30. I'm happy to receive comments or changes to this draft.
> towards versioned releases

- .github/workflows/weekly_tests.yml
Allow manual triggering of workflow `weekly_test` because it is not triggered when testing PRs (which is good), but when fixing failures of `weekly_test` it would be necessary
see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> allow manual running of weekly_test

- Simulations/DALES/botany_dx100m.yaml
- Simulations/DALES/botany_dx100m_nx1536.yaml
- Simulations/DALES/botany_dx100m_nx96.yaml
similar to the previous botany_dx_100m_nx1536, except:
* the domain size is smaller, 96 cells horizontally
* the simulation time is longer, 7 days.
Test script, to access the new datasets (loading catalog from my fork of the eurec4a-intake catalog):
```python
import matplotlib.pyplot as plt
import pandas as pd
from intake import open_catalog
url ="https://raw.githubusercontent.com/fjansson/eurec4a-intake/botany-96/Simulations/DALES/botany.yaml"
cat = open_catalog(url)
parameters = cat.dx100m.nx96.parameters.read()
varied_parameters = ['member','thls', 'u0', 'qt0', 'qt_lambda', 'thl_Gamma', 'wpamp', 'dudz', 'location']
df_parameters = pd.DataFrame.from_records(parameters)[varied_parameters]
print(df_parameters)
ds_2D = cat.dx100m.nx96['2D'].to_dask()
print(ds_2D)
ds_3D = …
```
> add DALES simulations botany_dx100m_nx96

- README.md
This is a followup to #31, adding a note about the possibility to install via `requirements.txt`.
> note about requirements in README

- .github/workflows/weekly_tests.yml
- README.md
The badge on the readme page (https://github.com/eurec4a/eurec4a-intake/workflows/eurec4a_intake/badge.svg) does not work correctly, e.g. it is currently set to "failing" although all pipelines succeed. The link seems to be non-standard and since we have two workflows with the same name (`eurec4a_intake`) some confusion might be caused. This PR does:
- fix link to badge
- use weekly_tests.yml as main health indicator
- change test name to be more descriptive
> Fix CI badge

- CHANGELOG.md
- CITATION.md
This tries to provide recommendations on how to cite the catalog following the discussion in #30:
- add instructions on how to cite the EUREC4A intake catalog
- add note that datasets within the catalog need to be explicitly referenced as well
- mention that the catalog itself cannot insure integrity of the datasets
> Add CITATION.md

- README.md
- requirements.txt
With intake 2.0.0 the weekly test currently fails with:
```
("missing 'module'", {'module': 'intake_xarray'})
ERROR tests/test_catalog.py - intake.catalog.exceptions.ValidationError: Catalog '/home/runner/work/eurec4a-intake/eurec4a-intake/catalog.yml' has validation errors:
```
Intake-2 is in beta, so we should limit it to previous versions for now.
> Limit intake to versions < 2.0.0

- CHANGELOG.md
- barbados/BCO/bco.yaml
- barbados/BCO/poldirad.yaml
This PR adds the gridded POLDIRAD dataset available at https://observations.ipsl.fr/aeris/eurec4a-data/BARBADOS/POLDIRAD/gridded_data/PPI_PCP_L2GRID_v1/
To easy the access to the dataset:
- 4203 files have been referenced with kerchunk
- time dimension has been added based on the filename
- variables `height`, `lat`, `lon`, `x_distance`, `y_distance` have been assumed to be constant with time
The script used for the generation of the kerchunk file is referenced in the history of the kerchunk-dataset and is available [here](https://gist.github.com/observingClouds/d134f581c16a94759abd47052cc83d2c#file-create_kerchunk_reference_poldirad_gridded-py)
> Add gridded POLDIRAD dataset

- CHANGELOG.md
- barbados/BCO/bco.yaml
- `flag` variable has been changed from `long` to `short` to support openDAP protocol
- fix for weekly test as old file is deleted
> Update BCO precipitation isotope product

- CHANGELOG.md
- Simulations/EUREC4A-MIP/warming/setup/bc.yaml
- Simulations/EUREC4A-MIP/warming/setup/deltas.yaml
add warming deltas provided by @torresalavez
> add EUREC4A-MIP warming deltas
